inherit_from: configs/Replica/replica.yaml
name: ro2
extent_size: 5.0 
lr_scale: 5.0
data:
  input_folder: '/mnt/nas_9/datasets/Replica/room2'
  output_folder: './output/Replica/room2'

tracking:
  T_color_weight: 0.2
  T_depth_weight: 1.0
  T_rot_lr: 0.0015
  T_tran_lr: 0.00215

mapping:
  M_color_weight: 0.8
  M_depth_weight: 0.25

optim_hyper:
  scaling_lr: None
  position_lr_init: None
  position_lr_final: None
  feature_lr: None